[project]
name = "lmf"
version = "0.1.0"
description = "A CLI for the langchain language model framework."
readme = "README.md"
requires-python = ">=3.11"
authors = [{name = "engisalor@github"}]
dependencies = [
    "click>=8.2.1",
    "huggingface-hub[cli]>=0.33.0",
    "kaleido>=1.0.0",
    "langchain-community>=0.3.25",
    "langchain-huggingface>=0.3.0",
    "langchain-ollama>=0.3.3",
    "langchain-openai>=0.3.35",
    "matplotlib>=3.10.7",
    "ollama>=0.5.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "plotly>=6.2.0",
    "sentence-transformers>=4.1.0",
    "tabulate>=0.9.0",
]

[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

dependencies = [
    "click>=8.2.1",
    "langchain-community>=0.3.25",
    "langchain-huggingface>=0.3.0",
    "langchain-ollama>=0.3.3",
    "ollama>=0.5.1",
    "sentence-transformers>=4.1.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # flake8-bandit
    "S",
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[project.scripts]
lmf = "lmf.main:cli"
agree = "lmf.agreement:agree"

[project.optional-dependencies]
extra = []
